In [3]:
#Ejercicio 1:  Simulación de una codificación binaria lineal CON RUIDO
import numpy as np

alfabeto="AÁBCDEÉFGHIÍJKLMNÑOÓPQRSTUÚVWXYZ .,;:()¿?¡!-0123456789aábcdeéfghiíjklmnñoópqrstuúvwxyz"
A=[[1,0,1,0,1,0,1,1,1],
[1,0,1,0,1,1,0,0,1],
[1,0,1,1,0,1,1,0,0],
[0,1,0,1,0,0,1,1,0],
[0,0,1,1,1,0,0,1,1],
[1,1,1,1,0,0,0,0,0]];

lista=[1,1,0,1,0,0,0,1,0,1,0,0,1,1,0,0,0,1,1,1,1,0,1,1,1,0,1,1,1,0,1,1,0,1,1,1,0,1,0,1,0,1,0,0,0,0,0,1,
       0,1,0,1,1,0,0,1,0,0,1,1,1,1,1,0,0,0,0,0,1,0,0,0,1,1,0,1,1,1,1,1,1,0,0,1,1,0,1,1,0,0,1,0,1,1,1,0,
       0,0,1,0,1,1,0,0,1,1,1,0,0,1,0,1,0,1,0,1,0,1,1,1,0,0,1,0,1,0,0,0,0,1,1,1,0,1,1,0,0,0,1,0,0,1,0,1,
       1,0,1,1,0,0,0,1,1,1,0,0,0,1,0,0,1,1,1,0,1,0,1,1,0,0,1,1,1,1,1,0,0,0,0,0,1,0,0,1,0,1,1,1,1,1,0,0,
       0,0,0,1,0,1,0,0,1,0,0,0,1,0,1,0,1,0,0,0,0,1,0,1,1,0,1,1,1,0,0,1,1,0,0,0,1,1,0,0,1,1,1,0,1,1,1,0,
       0,1,1,0,1,0,1,1,1,0,1,0,1,0,1,1,0,0,1,0,1,0,1,1,0,0,0,1,0,0,0,0,0,1,1,0,0,1,1,1,0,1,1,1,0,0,1,1,
       0,1,1,1,0,1,1,1,0,0,1,1,0,0,0,0,1,0,1,0,1,1,0,1,1,0,0,1,1,0,1,0,1,0,1,0,1,1,1,0,0,1,0,1,1,1,0,0,
       1,0,1,1,0,1,1,0,0,0,0,1,1,1,1,0,1,0,0,0,1,1,0,0,0,1,1,0,0,1,0,1,0,0,1,0,0,1,1,1,1,1,0,1,1,0,0,0,
       1,0,0,1,0,0,0,0,0,1,1,0,0,1,1,0,1,1,0,1,1,0,0,1,0,0,0,1,0,1,0,1,0,1,1,1,0,1,0,0,1,1,0,1,1,0,0,0,
       1,0,0,1,1,0,1,1,0,1,0,0,1,0,1,0,1,0,0,0,0,0,0,1,0,1,0,1,0,0,1,1,0,0,0,0,0,1,0,0,1,0,1,0,0,1,1,0,
       0,0,1,1,1,0,0,0,1,0,0,1,0,0,0,0,0,1,1,1,1,0,1,1,1,0,0,0,0,0,0,1,1,0,1,0,0,1,1,1,1,0,0,0,1,1,0,1,
       1,0,1,1,0,1,1,1,0,0,1,1,0,1,0,1,1,0,1,1,0,1,1,1,0,0,1,1,0,0,1,0,1,0,1,0,1,0,1,0,0,0,0,0,0,1,1,1,
       0,1,0,1,0,0,1,1,0,0,1,0,1,0,0,1,0,1,0,0,1,0,0,0,0,1,0,0,1,1,1,0,0,1,1,1,0,1,1,0,0,1,0,0,1,1,1,1,
       0,0,1,0,1,0,0,1,0,0,1,1,1,0,1,0,1,1,0,0,1,0,1,0,1,0,0,0,1,0,1,1,1,0,0,1,0,1,1,0,1,0,1,1,0,0,0,1,
       1,0,0,1,1,0,1,0,1,1,1,1,0,0,0,1,0,0,1,0,1,1,0,1,1,0,1,0,0,1,0,0,0,1,1,0,0,0,1,1,1,1,1,0,0,0,0,0,
       0,0,1,0,0,0,0,0,0,1,0,1,0,1,0,1,0,1,1,0,0,1,0,1,0,1,0,1,1,1,0,1,0,1,0,0,0,1,0,1,1,1,0,0,1,1,1,1,
       1,0,1,1,1,1,0,1,0,1,0,1,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,1,0,1,1,1,0,0,1,1,1,1,1,0,0,
       0,1,1,0,1,1,0,1,1,1,1,1,1,0,0,1,1,1,1,1,0,0,0,1,1,0,0,0,0,0,1,0,1,0,1,1,0,0,1,0,1,1,1,0,0,1,0,1,
       1,0,1,1,0,0,0,0,1,1,1,1,0,1,0,0,0,1,1,0,0,0,0,1,1,1,0,0,1,0,0,1,1,1,0,1,1,0,1,0,1,0,1,1,0,0,0,0,
       0,1,0,0,0,1,1,1,1,0,1,0,0,0,1,1,0,0,1,0,1,0,0,1,1,0,1,1,0,1,1,0,0,1,1,0,0,1,0,1,0,1,0,1,1,0,0,1,
       1,0,1,1,1,1,1,1,0,1,1,1,0,0,1,1,1,1,0,0,0,1,1,1,0,1,0,1,0,1,1,1,0,1,0,0,0,1,0,1,0,0,1,1,0,1,1,1,
       1,0,1,1,1,1,0,1,0,1,0,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,1,0,0,0,0,1,1,1,1,0,0,0,1,1,1,0,0,1,1,
       1,0,0,1,0,0,1,0,0,1,1,1,0,0,0,1,0,1,1,0,1,1,0,0,0,1,1,1,1,1,1,0,0,1,1,0,1,0,1,1,1,1,1,0,0,1,1,1,
       0,0,1,0,1,0,0,0,0,1,1,0,1,0,0,1,0,0,1,0,0,0,0,1,0,0,1,0,0,0,1,1,0,1,0,1,1,1,0,0,1,1,0,1,1,0,1,1,
       0,1,1,1,1,1,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,1,1,0,0,0,1,1,1,1,1,0,1,0,0,0,0,0,0,0,0,0,1,1,0,1,0,1,
       0,1,0,0,0,0,0,0,1,1,1,1,1,0,1,0,0,1,1,1,0,0,0,1,1,1,0,0,1,1,0,1,0,0,1,1,0,0,1,0,0,0,1,1,0,1,1,1,
       1,0,1,0,1,1,1,1,0,0,0,1,1,0,0,0,0,0,1,0,1,0,1,1,0,0,1,0,0,0,1,1,0,1,0,0,1,0,1,0,1,0,1,0,1,1,0,0,
       1,1,1,0,1,1,0,1,1,0,1,1,1,1,1,0,1,1,1,1,0,0,0,1,0,1,1,1,0,1,1,0,1,1,1,1,1,0,1,1,0,0,0,0,0,0,1,0,
       1,0,1,0,0,0,1,0,1,0,1,0,0,1,1,1,1,0,0,0,1,0,0,1,0,0,0,1,0,1,0,1,1,0,0,1,0,1,0,0,0,1,1,1,1,1,1,1,
       1,1,1,0,0,0,1,0,1,0,0,1,1,0,1,1,0,0,1,1,1,1,1,0,0,1,0,0,1,0,0,1,1,1,1,1,0,0,0,1,1,1,1,0,1,1,1,0,
       1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,1,0,1,1,0,0,0,1,0,1,1,0,0,1,0,1,0,1,0,1,0,1,1,1,0,1,1,
       1,1,1,1,1,0,1,1,1,0,0,1,1,1,0,0,0,1,1,0,1,1,0,0,0,1,0,1,0,0,0,1,1,0,0,1,1,1,1,1,0,1,0,1,1,1,1,1,
       0,0,0,1,0,1,0,1,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,1,1,0,0,1,0,1,0,1,0,1,0,1,1,1,1,1,0,0,0,0,1,0,0,
       1,0,0,1,0,0,1,1,0,0,1,1,1,0,0,1,0,1,0,1,0,0,0,0,0,1,0,0,1,0,1,0,0,1,1,0,0,0,1,1,1,1,1,1,0,0,1,0,
       0,1,1,0,0,0,1,1,0,0,1,1,1,0,1,1,1,0,0,0,1,0,0,0,0,0,1,0,0,0,1,1,0,1,1,0,0,0,1,0,1,1,1,1,0,0,0,1,
       1,1,1,0,1,1,0,1,1,0,0,0,1,0,0,1,0,0,1,1,0,1,1,0,1,1,1,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,1,0,1,0,1,0,
       0,0,1,1,1,0,0,1,0,0,1,1,1,1,1,0,1,1,0,0,1,0,0,0,1,1,0,1,0,1,0,1,0,1,0,1,1,0,1,1,0,0,1,1,0,0,1,0,
       1,0,1,0,1,0,1,1,1,0,1,1,0,1,1,1,0,1,1,1,0,0,1,1,1,0,0,1,1,1,1,1,0,0,1,1,1,0,1,0,0,0,0,0,0,1,1,1,
       1,1,1,1,1,1,0,1,0,0,0,0,0,1,0,1,0,0,1,1,0,1,0,1,0,1,0,0,0,1,1,1,0,0,1,1,0,0,1,0,1,1,0,0,0,1,0,1,
       0,1,0,0,1,0,0,1,0,0,1,0,1,1,1,0,0,1,1,0,1,0,0,1,1,0,1,0,1,0,1,1,1,0,0,0,0,0,1,0,1,1,0,0,1,0,1,0,
       1,0,1,0,0,0,0,0,0,1,1,0,1,0,1,1,0,0,0,1,0,1,1,0,0,1,0,0,1,1,1,1,1,0,1,0,1,0,0,1,0,0,1,0,0,1,0,1,
       0,0,1,1,0,1,1,0,1,1,0,0,1,1,1,0,0,0,0,1,1,1,1,0,0,0,1,0,1,1,1,0,0,1,0,1,0,1,1,0,0,1,0,0,1,0,1,0,
       1,0,0,1,0,1,0,1,0,0,1,0,1,1,0,1,1,0,0,0,0,0,1,0,1,1,1,1,1,0,0,1,0,1,0,1,0,0,0,0,1,0,0,0,0,1,1,1,
       1,0,1,1,1,0,1,0,1,1,1,1,0,1,0,0,1,1,1,0,1,1,1,0,1,0,0,1,0,1,0,1,0,1,1,1,0,0,0,0,0,0,1,0,0,1,0,0,
       1,0,0,0,1,1,1,1,0,1,0,0,1,0,1,0,1,0,1,0,1,0,1,1,0,1,0,0,0,1,1,0,0,0,1,1,0,1,0,0,0,1,0,0,1,0,0,0,
       0,0,0,1,0,0,0,0,1,1,1,0,0,1,1,0,1,0,1,1,1,0,1,0,1,1,1,0,0,1,1,0,0,1,1,0,0,0,1,1,1,0,0,1,1,0,0,0,
       1,0,1,1,1,1,1,1,0,0,0,1,0,1,1,0,0,1,0,1,1,0,0,1,0,1,0,0,1,0,1,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,0,0,
       1,0,0,0,1,1,1,1,1,0,1,1,0,0,1,1,1,1,1,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1,0,1,1,0,1,
       0,0,0,1,1,0,1,1,0,1,1,1,1,0,0,1,1,0,1,0,1,0,0,1,1,0,1,1,0,1,1,0,1,1,0,0,0,0,0,0,0,1,0,0,1,1,1,0,
       0,1,1,1,0,0,1,1,1,0,1,0,1,1,0,1,1,1,1,1,1,0,0,1,0,0,0,1,1,0,1,0,1,0,1,1,1,1,0,1,1,1,1,1,1,1,1,1,
       0,1,0,1,0,1,1,0,1,0,1,1,0,0,1,1,1,0,0,0,1,1,1,1,1,0,0,0,0,0,0,0,1,0,1,0,1,0,0,1,0,0,1,0,0,1,0,1,
       0,1,1,1,0,0,1,0,0,1,0,0,1,1,1,0,0,0,1,0,1,0,1,0,1,1,1,1,0,1,1,0,1,0,0,0,1,1,1,0,1,1,0,1,0,0,0,1,
       0,0,0,0,0,1,1,1,0,0,0,0,0,1,1,1,0,0,1,0,1,0,1,0,1,1,0,0,1,0,1,0,1,0,1,1,0,0,1,0,0,0,1,0,0,1,0,1,
       1,0,1,1,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,1,0,1,0,0,1,1,0,1,1,0,0,1,0,0,0,1,0,0,0,
       1,1,0,0,1,0,0,0,1,1,0,1,1,1,0,0,1,1,0,1,1,1,0,0,1,0,1,1,0,1,1,0,0,0,0,0,0,0,1,1,0,1,0,1,0,1,1,1,
       1,1,0,0,0,0,0,1,0,1,1,1,0,0,1,0,0,0,1,0,1,0,0,1,1,0,0,0,1,0,0,1,0,1,1,0,0,0,1,0,0,0,1,1,0,0,0,1,
       0,0,0,1,1,1,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,1,0,1,0,0,0,1,1,0,0,0,1,0,1,1,1,1,0,0,0,1,0,1,0,0,1,1,
       1,0,1,0,1,1,0,0,1,0,0,0,0,1,1,1,0,1,0,0,0,1,1,0,1,1,1,1,0,0,0,1,1,0,1,1,0,1,1,1,1,0,0,0,1,0,1,0,
       1,0,1,0,0,0,0,0,1,0,0,0,0,0,1,1,1,0,0,1,1,0,0,1,1,1,0,0,0,0,1,0,1,0,1,0,0,0,1,0,0,0,1,1,0,1,1,1,
       0,0,1,1,1,0,1,1,1,0,0,0,0,1,1,1,1,1,1,0,1,0,1,1,0,1,0,1,1,0,1,1,1,1,0,1,0,1,0,0,0,1,0,0,0,1,1,0,
       1,1,1,1,0,1,0,1,0,0,1,0,0,1,1,1,0,1,1,0,0,1,1,0,1,1,0,1,1,1,1,1,0,1,1,0,1,1,1,1,1,1,1,1,1,0,0,1,
       1,0,0,1,1,1,0,0,0,1,0,0,1,0,1,1,1,1,1,1,0,0,0,0,0,1,0,1,1,0,1,0,0,0,0,0,0,1,1,1,1,1,0,1,1,1,0,0,
       0,1,0,1,0,0,1,1,0,0,1,0,0,0,0,0,0,1,1,1,0,0,1,1,1,0,1,0,0,1,1,1,1,1,0,0,0,0,0,1,1,1,0,1,1,0,0,1,
       0,0,0,1,1,0,0,0,0,1,0,1,1,0,1,0,0,1,0,0,0,0,0,1,1,1,0,1,1,0,0,0,1,1,0,0,0,0,1,1,0,1,0,1,1,1,1,1,
       1,1,1,0,1,1,1,0,1,1,0,1,0,0,0,1,1,0,0,1,1,1,0,0,0,0,1,0,0,0,1,1,0,0,0,0,1,0,1,1,0,1,0,0,1,0,0,0,
       1,0,0,1,1,0,0,0,1,0,0,1,0,0,0,1,1,1,1,0,0,0,0,0,0,0,1,1,1,0,0,1,0,0,1,0,0,0,0,1,1,0,1,0,1,0]

#Algoritmo del lider

#Primera parte: Obtener matriz de control
transposeA = np.transpose(A)
identidad = np.identity(9)
matrizH = np.concatenate((transposeA, identidad), axis=1)
print("Matriz de control:",matrizH)

#Segunda parte: Corregir y € F^15
#I: Sindrome de y

numColA = np.shape(A)[1]
numColH = np.shape(matrizH)[1]

def obtenerCeros(numCeros):
    aux = []
    for i in range(numCeros):
        aux.append(0)
    return aux
    
def obtenerY(lista,n):
    final = [lista[i:i + n] for i in range(0, len(lista), n)]
    return final
    
listaPalabras=obtenerY(lista,15)
print("\nLista palabras y:",listaPalabras)

def obtenerSyndr(lista,matriz):
    syndrome = []
    for i in range(len(lista)):
        aux=lista[i]
        if(len(aux)==len(matriz[0])):
            auxT=np.transpose(aux)
            syndrome.append((matriz @ auxT).tolist())
    return syndrome 

listaSyndrom = obtenerSyndr(listaPalabras,matrizH)
#print("\nLista s:",listaSyndrom)

def sacarVectores(lista):
    result = []
    for i in range(len(lista)):
        result.append(metodoBinario2(lista[i]))
    return result

def metodoBinario2(vector):
    auxBinario=[]
    for i in range(len(vector)):
        if vector[i] != 0 and vector[i] !=1:
            if vector[i] %2 ==0:
                auxBinario.append(0)
            else:
                auxBinario.append(1)
        else:
            auxBinario.append(vector[i])
    return auxBinario

listaSyn2=sacarVectores(listaSyndrom)
print("\nLista sindrome de palabras:",listaSyn2)

def errorPatronPeso0(errores):
    listaCeros = []
    for i in range(numColH):
        listaCeros.append(0)
    errores.append(listaCeros)
    
    return errores

def errorPatronPeso1(errores):
    listaUnos=[]
    aumento=0;
    for i in range(numColH):
        for j in range(numColH):
            if j==aumento:
                listaUnos.append(1)
            else:
                listaUnos.append(0)
                
        aumento +=1
        errores.append(listaUnos)
        listaUnos=[]
        
    return errores

def calcularErrorPatronSegundo(errores):
    listaDos = []
    aumento=0;
    aumento2=0;
    for i in range(numColH):
        for j in range(numColH):
            for k in range(numColH):
                if aumento==aumento2:
                    aumento2 += 1
                if k == aumento:
                    listaDos.append(1)
                elif k == aumento2:
                    listaDos.append(1)
                else:
                    listaDos.append(0)
            aumento2 += 1
            if pesoDos(listaDos) and not(repetido(errores, listaDos)):
                errores.append(listaDos)
            listaDos = []
        aumento2 = 0
        aumento += 1

    return errores
   

#Determinar lista son peso 2
def pesoDos(aux):
    numUnos = 0
    for i in range(len(aux)):
        if aux[i] == 1:
            numUnos += 1
    if numUnos == 2:
        return True
    else:
        return False

def repetido(error, aux):
    if error.count(aux) > 0:
        return True
    else:
        return False
    
erroresPatrones=[]
erroresPatrones=errorPatronPeso0(erroresPatrones)
erroresPatrones=errorPatronPeso1(erroresPatrones)
erroresPatrones=calcularErrorPatronSegundo(erroresPatrones)
print("\nLista errores patrón:",erroresPatrones)

listaSdeE=sacarVectores(obtenerSyndr(erroresPatrones,matrizH))
print("\nLista sindromes de errores:",listaSdeE)

def sacarIndiceListaErrores(listaSynErr,listaSynPal):
    listaIndices=[]
    for i in range(len(listaSynPal)):
        indice=listaSynErr.index(listaSynPal[i])
        listaIndices.append(indice)
    return listaIndices
     
listaIndice=sacarIndiceListaErrores(listaSdeE,listaSyn2)

def restaYE(palabras,errores,indices):
    aux=[]
    for i in range(len(palabras)-1):
        aux.append(obtenerResta(palabras[i], errores[indices[i]]))
    return aux

def obtenerResta(palabra,error):
    aux=[]
    for i in range(len(palabra)):
        resta = palabra[i] - error[i]
        
        if resta == -1:
            aux.append(1)
        else: 
            aux.append(resta)
        
    return aux
    
print("\nLista corregida",restaYE(listaPalabras,erroresPatrones,listaIndice))
listaCorregida=restaYE(listaPalabras,erroresPatrones,listaIndice)

#==================================================Parte 3º Practica======================================================
numeroGeneratriz=6
def sacar6Primeros(lista):
    result = []
    for i in range(len(lista)):
        result.append(sacarVectores(lista[i]))
    return result

#obtenemos vectores de la lista resultado
def sacarVectores(vector):
    vectorTres = []
    for i in range(len(vector)):
        if i<numeroGeneratriz:
            vectorTres.append(vector[i])
    return vectorTres

resultado = sacar6Primeros(listaCorregida)
print("\nLista 6 primeros:",resultado)

# COMPRIMOS LO ANTERIOR EN UNA LISTA UNICA ===================================
ultimo = []
def listaUnica(resultadoB):
    for i in resultadoB:
        for j in i:
            ultimo.append(j)
    return ultimo

listaUniq = listaUnica(resultado);
print("\nLista unica:",listaUniq)

# DIVIDIMOS LA LISTA UNICA EN PORCIONES DE 7 ==================================
n2=7
aux = [listaUniq[i:i + n2] for i in range(0, len(listaUniq), n2)]
print("\nLista 7 porciones:",aux)

# DECODIFICACION DE LA FUENTE (POSICIONES) ====================================
def posicionesLista(lista):
    listaNum = []
    for i in range(len(lista)):
        listaNum.append(metodoBinario(lista[i]))
    return listaNum

def metodoBinario(numBin):
    numDec = 0
    potencia = 6  #tam - 1, 7-1
    for i in range(len(numBin)):
        numDec += numBin[i]*2**potencia
        potencia -= 1
    return numDec

listaDec = posicionesLista(aux)
print("\nLista posiciones:",listaDec)

#FUNCIONES REEMPLAZAR LOS DOBLE-ESPACIOS POR SALTOS DE LINEA ==========
def esSalto(msj):
    long = len(msj)
    if msj[long-1]==" " and msj[long-2]==" ":
        return True
    return False

def saltoLinea(msj):
    long = len(msj)-2
    aux = msj[0:long]
    aux += "\n"
    return aux

# A PARTIR DE LAS POSICIONES, OBTENEMOS LA LETRA CORRESPONDIENTE ===============
def sacarLetras(lista):
    listaLetras = ""
    for i in range(len(lista)):
        listaLetras += metodoLetras(lista[i])
        if esSalto(listaLetras):
            listaLetras = saltoLinea(listaLetras)
    return listaLetras

def metodoLetras(pos):
    carac = ""
    for i in range(len(alfabeto)):
        if(i==pos):
            carac = alfabeto[i]
    return carac;

mensajeFinal = sacarLetras(listaDec)
print("\nMensaje:")
print(mensajeFinal)

Matriz de control: [[1. 1. 1. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 0. 1. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [1. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]

Lista palabras y: [[1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0], [0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0], [1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0], [0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1], [1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0], [1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0], [1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1], [1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1], [0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1], [0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0], [0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1], [0, 1, 1, 0