In [7]:
alfabeto="ABCDEFGHIJKLMNÑOPQRSTUVWXYZ -";

p=2;

A=[
    [1,0,1,0,1,0,1],
    [0,1,0,1,0,1,1]
];

matrizG = [
    [1,0,1,0,1,0,1,0,],
    [0,1,0,1,0,1,0,1,],
];

lista=[1,1,1,1,1,1,1,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,0,0,1,0,1,0,1,0,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,1,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,1,1,0,1,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,0,0,1,0,1,0,1,0,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,0,1,0,1,0,1,0,1,0,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,1,0,1,1,0,1,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,1,1,0,1,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,1,0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,0,1,0,1,0,1,0,1,0,1,1,1,1,1,1,1,1,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,1,1,0,1,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,1,1,1,1,1,1,1,1,1,0,1,0,1,0,1,0,1,0,1,1,1,1,1,1,1,1,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,1,0,1,0,1,0,1,0,1,1,0,1,0,1,0,1,0,1,1,0,1,0,1,0,1,0,1,1,0,1,0,1,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,0,0,1,0,1,0,1,0,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,0,1,0,1,0,1,0,1,0,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,0,1,0,1,0,1,0,1,0,1,0]

In [23]:
print(len(alfabeto))

final = []
# usando compresiones de listas
final = [lista[i:i + 9] for i in range(0, len(lista), 9)]

# OBTENEMOS DE LA LISTA DE 6 EN 6, LOS 3 PRIMEROS VALORES =====================
def sacar3Primeros(lista):
    result = []
    for i in range(len(lista)):
        result.append(sacarVectores(lista[i]))
    return result

#obtenemos vectores de la lista resultado
def sacarVectores(vector):
    vectorTres = []
    for i in range(len(vector)):
        if i<2:
            vectorTres.append(vector[i])
    return vectorTres

resultado = sacar3Primeros(final)
print("\nLista 3 primeros:",resultado)

# COMPRIMOS LO ANTERIOR EN UNA LISTA UNICA ===================================
ultimo = []
def listaUnica(resultadoB):
    for i in resultadoB:
        for j in i:
            ultimo.append(j)
    return ultimo

listaUniq = listaUnica(resultado);
print("\nLista unica:",listaUniq)

# DIVIDIMOS LA LISTA UNICA EN PORCIONES DE 7 (dividimos en log2(alf)) ==================================
n2=5
aux = [listaUniq[i:i + n2] for i in range(0, len(listaUniq), n2)]
print("\nLista 7 porciones:",aux)

# DECODIFICACION DE LA FUENTE (POSICIONES) ====================================
def posicionesLista(lista):
    listaNum = []
    for i in range(len(lista)):
        listaNum.append(metodoBinario(lista[i]))
    return listaNum

def metodoBinario(numBin):
    numDec = 0
    potencia = n2-1
    for i in range(len(numBin)):
        numDec += numBin[i]*2**potencia
        potencia -= 1
    return numDec

listaDec = posicionesLista(aux)
print("\nLista posiciones:",listaDec)

# A PARTIR DE LAS POSICIONES, OBTENEMOS LA LETRA CORRESPONDIENTE ===============
def sacarLetras(lista):
    listaLetras = ""
    for i in range(len(lista)):
        listaLetras += metodoLetras(lista[i])
    return listaLetras

def metodoLetras(pos):
    carac = ""
    for i in range(len(alfabeto)):
        if(i==pos):
            carac = alfabeto[i]
    return carac;

mensajeFinal = sacarLetras(listaDec)
print("\nMensaje:",mensajeFinal)

29

Lista 3 primeros: [[1, 1], [1, 0], [0, 1], [1, 1], [0, 0], [1, 1], [0, 1], [1, 1], [0, 0], [0, 0], [1, 0], [0, 1], [0, 0], [1, 1], [1, 1], [0, 0], [0, 0], [1, 0], [0, 0], [0, 0], [0, 1], [1, 0], [1, 0], [0, 0], [1, 1], [0, 1], [1, 1], [1, 1], [1, 0], [1, 1], [0, 0], [0, 0], [1, 0], [1, 0], [0, 0], [0, 1], [1, 0], [1, 0], [0, 0], [0, 0], [1, 0], [0, 1], [0, 0], [1, 0], [0, 0], [0, 1], [1, 1], [1, 1], [1, 0], [1, 1], [1, 0], [0, 1], [1, 0], [1, 0], [0, 0], [0, 1], [1, 0], [1, 1], [1, 0], [1, 1], [1, 0], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 0], [0, 0], [0, 0], [1, 1], [0, 1], [1, 1], [1, 1], [1, 0], [1, 1], [1, 1], [1, 0], [0]]

Lista unica: [1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0,

In [21]:
import numpy as np

alf="ABCDEFGHIJKLMNÑOPQRSTUVWXYZ -"

p=2

A=[
    [1,0,1,0,1,0,1],
    [0,1,0,1,0,1,1]
];

matrizG = [
    [1,0,1,0,1,0,1,0,1],
    [0,1,0,1,0,1,0,1,1],
];

d=5

lista=[0,0,1,1,1,1,1,1,0,0,1,1,0,1,0,1,0,1,1,0,0,1,0,1,0,1,1,0,1,1,0,1,0,1,0,1,0,0,1,1,1,1,1,1,0,1,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,1,0,0,1,0,1,0,1,1,0,0,1,1,1,1,1,1,0,1,0,0,1,0,1,0,1,1,0,0,1,1,1,1,1,1,0,0,0,1,1,1,1,1,1,0,1,1,0,0,0,0,0,0,0,0,1,1,0,1,0,1,0,1,1,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,1,0,0,1,0,1,0,1,1,0,1,1,0,1,0,1,0,1,0,0,1,1,1,1,1,1,0,0,1,1,0,1,0,1,0,1,1,1,0,0,0,0,0,0,0,1,0,0,1,0,1,0,1,1,1,1,0,0,0,0,0,0,0,0,1,1,0,1,0,1,0,1,1,0,0,1,0,1,0,1,1,0,0,1,1,1,1,1,1,0,0,1,1,0,1,0,1,0,1,1,1,0,0,0,0,0,0,0,1,0,0,1,0,1,0,1,1,1,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,0,1,0,0,1,0,1,0,1,1,1,1,0,0,0,0,0,0,0,1,0,0,1,0,1,0,1,1,0,1,1,0,1,0,1,0,1,0,0,1,1,1,1,1,1,0,0,0,1,1,1,1,1,1,0,0,0,1,1,1,1,1,1,0,1,0,0,1,0,1,0,1,1,0,1,1,0,1,0,1,0,1,1,1,0,0,0,0,0,0,0,1,0,0,1,0,1,0,1,1,1,0,0,1,0,1,0,1,1,1,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,0,1,0,0,1,0,1,0,1,1,1,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,1,0,0,1,0,1,0,1,1,1,1,0,0,0,0,0,0,0,0,1,1,0,1,0,1,0,1,1,0,0,1,0,1,0,1,1,1,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,0,0,0,1,1,1,1,1,1,0,0,0,1,1,1,1,1,1,0,1,0,0,1,0,1,0,1,1,0,1,1,0,1,0,1,0,1,1,1,0,0,0,0,0,0,0,0,1,1,0,1,0,1,0,1,1,0,0,1,0,1,0,1,1,0,0,1,1,1,1,1,1,0,0,1,1,0,1,0,1,0,1,0,0,1,1,1,1,1,1,0,1,0,0,1,0,1,0,1,1,0,0,1,1,1,1,1,1,0,1,0,0,1,0,1,0,1,1,0,0,1,1,1,1,1,1,0,1,1,0,0,0,0,0,0,0,0,1,1,0,1,0,1,0,1,0,1,1,0,1,0,1,0,1,0,1,1,0,1,0,1,0,1,0,1,1,0,1,0,1,0,1,0,1,1,0,1,0,1,0,1,1,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,1,0,0,1,0,1,0,1,1,0,1,1,0,1,0,1,0,1,0,0,1,1,1,1,1,1,0,0,0,1,1,1,1,1,1,0,0,0,1,1,1,1,1,1,0,1,0,0,1,0,1,0,1,1,0,0,1,1,1,1,1,1,0,0,0,1,1,1,1,1,1,0,1,1,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,0,0,1,1,0,1,0,1,0,1,0]

In [23]:
#Primera parte: Obtener matriz de control
transposeA = np.transpose(A)
# len fila num caracters A
identidad = np.identity(7)
matrizH = np.concatenate((transposeA, identidad), axis=1)
print("Matriz de control:",matrizH)

#Segunda parte: Corregir y € F^15
#I: Sindrome de y

numColA = np.shape(A)[1]
numColH = np.shape(matrizH)[1]
print(numColH)

def obtenerCeros(numCeros):
    aux = []
    for i in range(numCeros):
        aux.append(0)
    return aux
    
def obtenerY(lista,n):
    final = [lista[i:i + n] for i in range(0, len(lista), n)]
    return final
    
listaPalabras=obtenerY(lista,numColH)
print("\nLista palabras y:",listaPalabras)

def obtenerSyndr(lista,matriz):
    syndrome = []
    for i in range(len(lista)):
        aux=lista[i]
        if(len(aux)==len(matriz[0])):
            auxT=np.transpose(aux)
            syndrome.append((matriz @ auxT).tolist())
    return syndrome 

listaSyndrom = obtenerSyndr(listaPalabras,matrizH)
#print("\nLista s:",listaSyndrom)

def sacarVectores(lista):
    result = []
    for i in range(len(lista)):
        result.append(metodoBinario2(lista[i]))
    return result

def metodoBinario2(vector):
    auxBinario=[]
    for i in range(len(vector)):
        if vector[i] != 0 and vector[i] !=1:
            if vector[i] %2 ==0:
                auxBinario.append(0)
            else:
                auxBinario.append(1)
        else:
            auxBinario.append(vector[i])
    return auxBinario

listaSyn2=sacarVectores(listaSyndrom)
print("\nLista sindrome de palabras:",listaSyn2)

def errorPatronPeso0(errores):
    listaCeros = []
    for i in range(numColH):
        listaCeros.append(0)
    errores.append(listaCeros)
    
    return errores

def errorPatronPeso1(errores):
    listaUnos=[]
    aumento=0;
    for i in range(numColH):
        for j in range(numColH):
            if j==aumento:
                listaUnos.append(1)
            else:
                listaUnos.append(0)
                
        aumento +=1
        errores.append(listaUnos)
        listaUnos=[]
        
    return errores

def calcularErrorPatronSegundo(errores):
    listaDos = []
    aumento=0;
    aumento2=0;
    for i in range(numColH):
        for j in range(numColH):
            for k in range(numColH):
                if aumento==aumento2:
                    aumento2 += 1
                if k == aumento:
                    listaDos.append(1)
                elif k == aumento2:
                    listaDos.append(1)
                else:
                    listaDos.append(0)
            aumento2 += 1
            if pesoDos(listaDos) and not(repetido(errores, listaDos)):
                errores.append(listaDos)
            listaDos = []
        aumento2 = 0
        aumento += 1

    return errores
   

#Determinar lista son peso 2
def pesoDos(aux):
    numUnos = 0
    for i in range(len(aux)):
        if aux[i] == 1:
            numUnos += 1
    if numUnos == 2:
        return True
    else:
        return False

def repetido(error, aux):
    if error.count(aux) > 0:
        return True
    else:
        return False
    
erroresPatrones=[]
erroresPatrones=errorPatronPeso0(erroresPatrones)
erroresPatrones=errorPatronPeso1(erroresPatrones)
erroresPatrones=calcularErrorPatronSegundo(erroresPatrones)
print("\nLista errores patrón:",erroresPatrones)

listaSdeE=sacarVectores(obtenerSyndr(erroresPatrones,matrizH))
print("\nLista sindromes de errores:",listaSdeE)
print("\nNumero sindromes de errores:",len(listaSdeE))

def sacarIndiceListaErrores(listaSynErr,listaSynPal):
    listaIndices=[]
    for i in range(len(listaSynPal)):
        indice=listaSynErr.index(listaSynPal[i])
        listaIndices.append(indice)
    return listaIndices
     
listaIndice=sacarIndiceListaErrores(listaSdeE,listaSyn2)

def restaYE(palabras,errores,indices):
    aux=[]
    for i in range(len(palabras)-1):
        aux.append(obtenerResta(palabras[i], errores[indices[i]]))
    return aux

def obtenerResta(palabra,error):
    aux=[]
    for i in range(len(palabra)):
        resta = palabra[i] - error[i]
        
        if resta == -1:
            aux.append(1)
        else: 
            aux.append(resta)
        
    return aux
    
print("\nLista corregida",restaYE(listaPalabras,erroresPatrones,listaIndice))
listaCorregida=restaYE(listaPalabras,erroresPatrones,listaIndice)

#==================================================Parte 3º Practica======================================================
numeroGeneratriz=2
def sacar6Primeros(lista):
    result = []
    for i in range(len(lista)):
        result.append(sacarVectores(lista[i]))
    return result

#obtenemos vectores de la lista resultado
def sacarVectores(vector):
    vectorTres = []
    for i in range(len(vector)):
        if i<numeroGeneratriz:
            vectorTres.append(vector[i])
    return vectorTres

resultado = sacar6Primeros(listaCorregida)
print("\nLista 6 primeros:",resultado)

# COMPRIMOS LO ANTERIOR EN UNA LISTA UNICA ===================================
ultimo = []
def listaUnica(resultadoB):
    for i in resultadoB:
        for j in i:
            ultimo.append(j)
    return ultimo

listaUniq = listaUnica(resultado);
print("\nLista unica:",listaUniq)

# DIVIDIMOS LA LISTA UNICA EN PORCIONES DE 7 ==================================
#log sup base 2 de len(alf)
n2=5
aux = [listaUniq[i:i + n2] for i in range(0, len(listaUniq), n2)]
print("\nLista 7 porciones:",aux)

# DECODIFICACION DE LA FUENTE (POSICIONES) ====================================
def posicionesLista(lista):
    listaNum = []
    for i in range(len(lista)):
        listaNum.append(metodoBinario(lista[i]))
    return listaNum

def metodoBinario(numBin):
    numDec = 0
    potencia = 4  #tam - 1, 7-1
    for i in range(len(numBin)):
        numDec += numBin[i]*2**potencia
        potencia -= 1
    return numDec

listaDec = posicionesLista(aux)
print("\nLista posiciones:",listaDec)

#FUNCIONES REEMPLAZAR LOS DOBLE-ESPACIOS POR SALTOS DE LINEA ==========
def esSalto(msj):
    long = len(msj)
    if msj[long-1]==" " and msj[long-2]==" ":
        return True
    return False

def saltoLinea(msj):
    long = len(msj)-2
    aux = msj[0:long]
    aux += "\n"
    return aux

# A PARTIR DE LAS POSICIONES, OBTENEMOS LA LETRA CORRESPONDIENTE ===============
def sacarLetras(lista):
    listaLetras = ""
    for i in range(len(lista)):
        listaLetras += metodoLetras(lista[i])
        if esSalto(listaLetras):
            listaLetras = saltoLinea(listaLetras)
    return listaLetras

def metodoLetras(pos):
    carac = ""
    for i in range(len(alfabeto)):
        if(i==pos):
            carac = alfabeto[i]
    return carac;

mensajeFinal = sacarLetras(listaDec)
print("\nMensaje:")
print(mensajeFinal)

Matriz de control: [[1. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 1. 0.]
 [1. 1. 0. 0. 0. 0. 0. 0. 1.]]
9

Lista palabras y: [[0, 0, 1, 1, 1, 1, 1, 1, 0], [0, 1, 1, 0, 1, 0, 1, 0, 1], [1, 0, 0, 1, 0, 1, 0, 1, 1], [0, 1, 1, 0, 1, 0, 1, 0, 1], [0, 0, 1, 1, 1, 1, 1, 1, 0], [1, 1, 0, 0, 0, 0, 0, 0, 0], [1, 1, 0, 0, 0, 0, 0, 0, 0], [1, 1, 0, 0, 0, 0, 0, 0, 0], [1, 0, 0, 1, 0, 1, 0, 1, 1], [0, 0, 1, 1, 1, 1, 1, 1, 0], [1, 0, 0, 1, 0, 1, 0, 1, 1], [0, 0, 1, 1, 1, 1, 1, 1, 0], [0, 0, 1, 1, 1, 1, 1, 1, 0], [1, 1, 0, 0, 0, 0, 0, 0, 0], [0, 1, 1, 0, 1, 0, 1, 0, 1], [1, 1, 0, 0, 0, 0, 0, 0, 0], [1, 1, 0, 0, 0, 0, 0, 0, 0], [1, 0, 0, 1, 0, 1, 0, 1, 1], [0, 1, 1, 0, 1, 0, 1, 0, 1], [0, 0, 1, 1, 1, 1, 1, 1, 0], [0, 1, 1, 0, 1, 0, 1, 0, 1], [1, 1, 0, 0, 0, 0, 0, 0, 0], [1, 0, 0, 1, 0, 1, 0, 1, 1], [1, 1, 0, 0, 0, 0, 0, 0, 0], [0, 1, 1, 0, 1, 0, 1, 0, 1], [1, 0, 0, 1, 0, 1, 0, 1

In [1]:
alfabeto="ABCDEFGHIJKLMNÑOPQRSTUVWXYZ -"

p=11

A=[
    [2,3,4,5],
    [6,7,8,9],
    [10,1,2,3]
];

matrizG = [
    [1,0,0,2,3,4,5],
    [0,1,0,6,7,8,9],
    [0,0,1,10,1,2,3]
];


lista=[2,6,2,5,6,5,4,5,0,2,8,6,2,9,0,0,1,10,1,2,3,1,0,1,1,4,6,8,0,8,1,3,2,0,9,4,2,5,4,9,9,9,0,4,1,1,7,1,6,0,2,5,7,8,4,0,0,2,1,0,4,7,10,10,0,4,5,1,4,7,1,7,1,10,9,7,5,5,1,4,1,4,3,2,2,5,1,0,9,6,3,8,0,8,8,10,4,9,1,2,2,1,8,2,7,5,1,7,9,7,9,0,1,10,0,7,7,7,7,8,0,3,2,5,5,5,1,4,2,2,0,7,3,5,2,6,5,2,4,6]


In [22]:
print(len(alfabeto))

final = []
# usando compresiones de listas
final = [lista[i:i + 7] for i in range(0, len(lista), 7)]

# OBTENEMOS DE LA LISTA DE 6 EN 6, LOS 3 PRIMEROS VALORES =====================
def sacar3Primeros(lista):
    result = []
    for i in range(len(lista)):
        result.append(sacarVectores(lista[i]))
    return result

#obtenemos vectores de la lista resultado
def sacarVectores(vector):
    vectorTres = []
    for i in range(len(vector)):
        if i<3:
            vectorTres.append(vector[i])
    return vectorTres

resultado = sacar3Primeros(final)
print("\nLista 3 primeros:",resultado)

# COMPRIMOS LO ANTERIOR EN UNA LISTA UNICA ===================================
ultimo = []
def listaUnica(resultadoB):
    for i in resultadoB:
        for j in i:
            ultimo.append(j)
    return ultimo

listaUniq = listaUnica(resultado);
print("\nLista unica:",listaUniq)

# DIVIDIMOS LA LISTA UNICA EN PORCIONES DE 7 (dividimos en logQ(alf)) ==================================
n2=2
aux = [listaUniq[i:i + n2] for i in range(0, len(listaUniq), n2)]
print("\nLista 7 porciones:",aux)

# DECODIFICACION DE LA FUENTE (POSICIONES) ====================================
def posicionesLista(lista):
    listaNum = []
    for i in range(len(lista)):
        listaNum.append(metodoBinario(lista[i]))
    return listaNum

#La p cambia 
def metodoBinario(numBin):
    numDec = 0
    potencia = n2-1
    for i in range(len(numBin)):
        numDec += numBin[i]*p**potencia
        potencia -= 1
    return numDec

listaDec = posicionesLista(aux)
print("\nLista posiciones:",listaDec)

# A PARTIR DE LAS POSICIONES, OBTENEMOS LA LETRA CORRESPONDIENTE ===============
def sacarLetras(lista):
    listaLetras = ""
    for i in range(len(lista)):
        listaLetras += metodoLetras(lista[i])
    return listaLetras

def metodoLetras(pos):
    carac = ""
    for i in range(len(alfabeto)):
        if(i==pos):
            carac = alfabeto[i]
    return carac;

mensajeFinal = sacarLetras(listaDec)
print("\nMensaje:",mensajeFinal)

29

Lista 3 primeros: [[2, 6, 2], [5, 0, 2], [0, 0, 1], [1, 0, 1], [0, 8, 1], [4, 2, 5], [0, 4, 1], [0, 2, 5], [0, 2, 1], [10, 0, 4], [1, 7, 1], [5, 1, 4], [2, 5, 1], [8, 0, 8], [1, 2, 2], [5, 1, 7], [1, 10, 0], [8, 0, 3], [1, 4, 2], [5, 2, 6]]

Lista unica: [2, 6, 2, 5, 0, 2, 0, 0, 1, 1, 0, 1, 0, 8, 1, 4, 2, 5, 0, 4, 1, 0, 2, 5, 0, 2, 1, 10, 0, 4, 1, 7, 1, 5, 1, 4, 2, 5, 1, 8, 0, 8, 1, 2, 2, 5, 1, 7, 1, 10, 0, 8, 0, 3, 1, 4, 2, 5, 2, 6]

Lista 7 porciones: [[2, 6], [2, 5], [0, 2], [0, 0], [1, 1], [0, 1], [0, 8], [1, 4], [2, 5], [0, 4], [1, 0], [2, 5], [0, 2], [1, 10], [0, 4], [1, 7], [1, 5], [1, 4], [2, 5], [1, 8], [0, 8], [1, 2], [2, 5], [1, 7], [1, 10], [0, 8], [0, 3], [1, 4], [2, 5], [2, 6]]

Lista posiciones: [28, 27, 2, 0, 12, 1, 8, 15, 27, 4, 11, 27, 2, 21, 4, 18, 16, 15, 27, 19, 8, 13, 27, 18, 21, 8, 3, 15, 27, 28]

Mensaje: - CAMBIO EL CUERPO SIN RUIDO -


In [1]:
import numpy as np
from itertools import product

alfabeto="ABCDEFGHIJKLMNÑOPQRSTUVWXYZ -"

p=7

A=[
    [2,3,4,5],
    [6,1,2,3]
];


matrizG = [
    [1,0,2,3,4,5],
    [0,1,6,1,2,3]
];

d=5

lista=[5,1,1,5,2,6,4,0,0,1,3,5,4,1,5,5,6,0,6,5,3,0,3,6,6,2,4,3,6,2,0,6,3,0,3,
       6,1,4,0,1,3,5,6,1,5,2,4,6,5,4,3,0,3,6,4,6,0,3,2,1,1,3,0,3,2,1,1,5,3,4,
       1,5,3,5,5,2,4,6,6,3,5,5,6,0,1,0,3,0,3,6,0,3,0,1,3,5,1,4,1,5,2,6]


In [20]:
#Primera parte: Obtener matriz de control
transposeA = np.transpose(A)
# len fila num caracters A
identidad = np.identity(4)
matrizH = np.concatenate((transposeA, identidad), axis=1)
print("Matriz de control:",matrizH)

#Segunda parte: Corregir y € F^15
#I: Sindrome de y

numColA = np.shape(A)[1]
numColH = np.shape(matrizH)[1]
print("\nNumero colunmas H:",numColH)

def obtenerCeros(numCeros):
    aux = []
    for i in range(numCeros):
        aux.append(0)
    return aux
    
def obtenerY(lista,n):
    final = [lista[i:i + n] for i in range(0, len(lista), n)]
    return final
    
listaPalabras=obtenerY(lista,numColH)
print("\nLista palabras y:",listaPalabras)

def obtenerSyndr(lista,matriz):
    syndrome = []
    for i in range(len(lista)):
        aux=lista[i]
        if(len(aux)==len(matriz[0])):
            auxT=np.transpose(aux)
            syndrome.append((matriz @ auxT).tolist())
    return syndrome 

listaSyndrom = obtenerSyndr(listaPalabras,matrizH)
#print("\nLista s:",listaSyndrom)

def sacarVectores(lista):
    result = []
    for i in range(len(lista)):
        result.append(metodoNoBinario(lista[i]))
    return result

def metodoNoBinario(vector):
    auxBinario=[]
    for i in range(len(vector)):
        auxBinario.append(vector[i]%p)
    return auxBinario

listaSyn2=sacarVectores(listaSyndrom)
print("\nLista sindrome de palabras:",listaSyn2)

def errorPatronPeso0(errores):
    listaCeros = []
    for i in range(numColH):
        listaCeros.append(0)
    errores.append(listaCeros)
    
    return errores

def errorPatronPeso1(errores):
    listaUnos=[]
    pos=0
    num=1
    for k in range(p-1):
        for i in range(numColH):
            for j in range(numColH):
                if j==pos:
                    listaUnos.append(num)
                else:
                    listaUnos.append(0)
            pos +=1
            errores.append(listaUnos)
            listaUnos=[]
        pos=0
        num +=1
    return errores

lista_nueva = []
def errorPatronNuevo(error):
    a = [0,1,2,3,4,5,6]
    lista_nueva=list(product(a, repeat=6))
    
    for i in range(len(lista_nueva)):
        if pesoDos(lista_nueva[i]) and not(repetido(error,lista_nueva[i])):
            error.append(list(lista_nueva[i]))
    return error

#Determinar lista son peso 2
def pesoDos(aux):
    numUnos = 0
    for i in range(len(aux)):
        if aux[i] != 0:
            numUnos += 1
    if numUnos == 2:
        return True
    else:
        return False

def repetido(error, aux):
    if error.count(aux) > 0:
        return True
    else:
        return False
    
erroresPatrones=[]
erroresPatrones=errorPatronPeso0(erroresPatrones)
erroresPatrones=errorPatronPeso1(erroresPatrones)
#erroresPatrones=calcularErrorPatronSegundo(erroresPatrones)
erroresPatrones = errorPatronNuevo(erroresPatrones)
print("\nLista errores patrón:",erroresPatrones)

listaSdeE=sacarVectores(obtenerSyndr(erroresPatrones,matrizH))
print("\nLista sindromes de errores:",listaSdeE)
print("\nNumero sindromes de errores:",len(listaSdeE))

def sacarIndiceListaErrores(listaSynErr,listaSynPal):
    listaIndices=[]
    for i in range(len(listaSynPal)):
        indice=listaSynErr.index(listaSynPal[i])
        listaIndices.append(indice)
    return listaIndices
     
listaIndice=sacarIndiceListaErrores(listaSdeE,listaSyn2)

def restaYE(palabras,errores,indices):
    aux=[]
    for i in range(len(palabras)):
        aux.append(obtenerResta(palabras[i], errores[indices[i]]))
    return aux

def obtenerResta(palabra,error):
    aux=[]
    for i in range(len(palabra)):
        resta = palabra[i] - error[i]
        aux.append((p-resta)%p)
        
    return aux
    
print("\nLista corregida",restaYE(listaPalabras,erroresPatrones,listaIndice))
listaCorregida=restaYE(listaPalabras,erroresPatrones,listaIndice)

#==================================================Parte 3º Practica======================================================
numeroGeneratriz=2
def sacar6Primeros(lista):
    result = []
    for i in range(len(lista)):
        result.append(sacarVectores(lista[i]))
    return result

#obtenemos vectores de la lista resultado
def sacarVectores(vector):
    vectorTres = []
    for i in range(len(vector)):
        if i<numeroGeneratriz:
            vectorTres.append(vector[i])
    return vectorTres

resultado = sacar6Primeros(listaCorregida)
print("\nLista 6 primeros:",resultado)

# COMPRIMOS LO ANTERIOR EN UNA LISTA UNICA ===================================
ultimo = []
def listaUnica(resultadoB):
    for i in resultadoB:
        for j in i:
            ultimo.append(j)
    return ultimo

listaUniq = listaUnica(resultado);
print("\nLista unica:",listaUniq)

# DIVIDIMOS LA LISTA UNICA EN PORCIONES DE 7 ==================================
#log sup base 2 de len(alf)
n2=2
aux = [listaUniq[i:i + n2] for i in range(0, len(listaUniq), n2)]
print("\nLista 7 porciones:",aux)

# DECODIFICACION DE LA FUENTE (POSICIONES) ====================================
def posicionesLista(lista):
    listaNum = []
    for i in range(len(lista)):
        listaNum.append(metodoBinario(lista[i]))
    return listaNum

def metodoBinario(numBin):
    numDec = 0
    potencia = n2-1  #tam - 1, 7-1
    for i in range(len(numBin)):
        numDec += numBin[i]*p**potencia
        potencia -= 1
    return numDec

listaDec = posicionesLista(aux)
print("\nLista posiciones:",listaDec)

#FUNCIONES REEMPLAZAR LOS DOBLE-ESPACIOS POR SALTOS DE LINEA ==========
def esSalto(msj):
    long = len(msj)
    if msj[long-1]==" " and msj[long-2]==" ":
        return True
    return False

def saltoLinea(msj):
    long = len(msj)-2
    aux = msj[0:long]
    aux += "\n"
    return aux

# A PARTIR DE LAS POSICIONES, OBTENEMOS LA LETRA CORRESPONDIENTE ===============
def sacarLetras(lista):
    listaLetras = ""
    for i in range(len(lista)):
        listaLetras += metodoLetras(lista[i])
        if esSalto(listaLetras):
            listaLetras = saltoLinea(listaLetras)
    return listaLetras

def metodoLetras(pos):
    carac = ""
    for i in range(len(alfabeto)):
        if(i==pos):
            carac = alfabeto[i]
    return carac;

mensajeFinal = sacarLetras(listaDec)
print("\nMensaje:")
print(mensajeFinal)

Matriz de control: [[2. 6. 1. 0. 0. 0.]
 [3. 1. 0. 1. 0. 0.]
 [4. 2. 0. 0. 1. 0.]
 [5. 3. 0. 0. 0. 1.]]

Numero colunmas H: 6

Lista palabras y: [[5, 1, 1, 5, 2, 6], [4, 0, 0, 1, 3, 5], [4, 1, 5, 5, 6, 0], [6, 5, 3, 0, 3, 6], [6, 2, 4, 3, 6, 2], [0, 6, 3, 0, 3, 6], [1, 4, 0, 1, 3, 5], [6, 1, 5, 2, 4, 6], [5, 4, 3, 0, 3, 6], [4, 6, 0, 3, 2, 1], [1, 3, 0, 3, 2, 1], [1, 5, 3, 4, 1, 5], [3, 5, 5, 2, 4, 6], [6, 3, 5, 5, 6, 0], [1, 0, 3, 0, 3, 6], [0, 3, 0, 1, 3, 5], [1, 4, 1, 5, 2, 6]]

Lista sindrome de palabras: [[3.0, 0.0, 3.0, 6.0], [1.0, 6.0, 5.0, 4.0], [5.0, 4.0, 3.0, 2.0], [3.0, 2.0, 2.0, 2.0], [0.0, 2.0, 6.0, 3.0], [4.0, 6.0, 1.0, 3.0], [5.0, 1.0, 1.0, 1.0], [2.0, 0.0, 2.0, 4.0], [2.0, 5.0, 3.0, 1.0], [2.0, 0.0, 2.0, 4.0], [6.0, 2.0, 5.0, 1.0], [0.0, 5.0, 1.0, 4.0], [6.0, 2.0, 5.0, 1.0], [0.0, 5.0, 1.0, 4.0], [5.0, 3.0, 0.0, 4.0], [4.0, 4.0, 2.0, 0.0], [6.0, 5.0, 0.0, 2.0]]

Lista errores patrón: [[0, 0, 0, 0, 0, 0], [1, 0, 0, 0, 0, 0], [0, 1, 0, 0, 0, 0], [0, 0, 1, 0, 0, 0], [0, 0,